name: "Google Find My Tools Web UI"
description: "Web UI for Google Find My Tools (Find Hub trackers & Android devices)"
version: "latest"
slug: "google_find_my_webui"
url: "https://github.com/ronmichel/GoogleFindMyToolsWebUi"
image: "ghcr.io/p6g9yhk6/googlefindmytools"
init: false
arch:
  - amd64
  - aarch64
startup: application
boot: auto
webui: "http://[HOST]:[PORT:4321]"
ports:
  4321/tcp: 4321
ports_description:
  4321/tcp: "Google Find My Tools Web UI"
tmpfs: true
environment:
  HTTP_USER: ""
  HTTP_PASSWORD: ""
  SECRETS_ENCRYPTION_KEY: ""
  HTTPS_ENABLED: "false"
  GFMT_TLS_SAN: ""
  TMPDIR: "/tmp"
